---

- tags:
    - setup-all
    - setup-focalboard
    - install-all
    - install-focalboard
  block:
    - when: focalboard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: focalboard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"


- tags:
    - setup-all
    - setup-focalboard
  block:
    - when: not focalboard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
